# 示例配置文件 - 请复制为实际配置文件并修改相应参数
database:
  host: "localhost"
  port: 5432
  user: "your_db_user"
  password: "your_db_password"
  dbname: "your_database"
  schema: "telemetry"
  sslmode: "disable"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "1h"

buffer:
  size: 50000
  flush_interval: "30s"
  batch_size: 1000

collector:
  bind_address: "0.0.0.0:57400"
  max_connections: 1000
  read_timeout: "30s"
  write_timeout: "30s"

logging:
  level: "info"
  format: "json"
  output: "console"  # 或 "file"
  file_path: "logs/telemetry.log"

performance:
  cpu_cores: 4
  enable_pprof: false
  pprof_port: 6060